// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.js to modify the generation of this file.
// Use app-components.shared.module.ts to modify the imports, etc of this module.
// Note: code-generation is optional! See ./.gitignore for directions to remove it,
// if you do not want it.

import { NgModule } from '@angular/core';
import { JssModule } from '@sitecore-jss/sitecore-jss-angular';
import { AppComponentsSharedModule } from './app-components.shared.module';
import { ContentBlockComponent } from './content-block/content-block.component';
import { GraphQLConnectedDemoComponent } from './graph-ql-connected-demo/graph-ql-connected-demo.component';
import { GraphQLIntegratedDemoComponent } from './graph-ql-integrated-demo/graph-ql-integrated-demo.component';
import { GraphQLLayoutComponent } from './graph-ql-layout/graph-ql-layout.component';
import { StyleguideComponentParamsComponent } from './styleguide-component-params/styleguide-component-params.component';
import { StyleguideCustomRouteTypeComponent } from './styleguide-custom-route-type/styleguide-custom-route-type.component';
import { StyleguideEditFrameComponent } from './styleguide-edit-frame/styleguide-edit-frame.component';
import { StyleguideFieldUsageCheckboxComponent } from './styleguide-field-usage-checkbox/styleguide-field-usage-checkbox.component';
import { StyleguideFieldUsageContentListComponent } from './styleguide-field-usage-content-list/styleguide-field-usage-content-list.component';
import { StyleguideFieldUsageCustomComponent } from './styleguide-field-usage-custom/styleguide-field-usage-custom.component';
import { StyleguideFieldUsageDateComponent } from './styleguide-field-usage-date/styleguide-field-usage-date.component';
import { StyleguideFieldUsageFileComponent } from './styleguide-field-usage-file/styleguide-field-usage-file.component';
import { StyleguideFieldUsageImageComponent } from './styleguide-field-usage-image/styleguide-field-usage-image.component';
import { StyleguideFieldUsageItemLinkComponent } from './styleguide-field-usage-item-link/styleguide-field-usage-item-link.component';
import { StyleguideFieldUsageLinkComponent } from './styleguide-field-usage-link/styleguide-field-usage-link.component';
import { StyleguideFieldUsageNumberComponent } from './styleguide-field-usage-number/styleguide-field-usage-number.component';
import { StyleguideFieldUsageRichTextComponent } from './styleguide-field-usage-rich-text/styleguide-field-usage-rich-text.component';
import { StyleguideFieldUsageTextComponent } from './styleguide-field-usage-text/styleguide-field-usage-text.component';
import { StyleguideLayoutComponent } from './styleguide-layout/styleguide-layout.component';
import { StyleguideLayoutReuseComponent } from './styleguide-layout-reuse/styleguide-layout-reuse.component';
import { StyleguideLayoutTabsComponent } from './styleguide-layout-tabs/styleguide-layout-tabs.component';
import { StyleguideLayoutTabsTabComponent } from './styleguide-layout-tabs-tab/styleguide-layout-tabs-tab.component';
import { StyleguideMultilingualComponent } from './styleguide-multilingual/styleguide-multilingual.component';
import { StyleguideRouteFieldsComponent } from './styleguide-route-fields/styleguide-route-fields.component';
import { StyleguideSectionComponent } from './styleguide-section/styleguide-section.component';
import { StyleguideSitecoreContextComponent } from './styleguide-sitecore-context/styleguide-sitecore-context.component';
import { StyleguideTrackingComponent } from './styleguide-tracking/styleguide-tracking.component';

@NgModule({
  imports: [
    AppComponentsSharedModule,
    JssModule.withComponents([
      { name: 'ContentBlock', type: ContentBlockComponent },
      { name: 'GraphQLConnectedDemo', type: GraphQLConnectedDemoComponent },
      { name: 'GraphQLIntegratedDemo', type: GraphQLIntegratedDemoComponent },
      { name: 'GraphQLLayout', type: GraphQLLayoutComponent },
      { name: 'StyleguideComponentParams', type: StyleguideComponentParamsComponent },
      { name: 'StyleguideCustomRouteType', type: StyleguideCustomRouteTypeComponent },
      { name: 'StyleguideEditFrame', type: StyleguideEditFrameComponent },
      { name: 'StyleguideFieldUsageCheckbox', type: StyleguideFieldUsageCheckboxComponent },
      { name: 'StyleguideFieldUsageContentList', type: StyleguideFieldUsageContentListComponent },
      { name: 'StyleguideFieldUsageCustom', type: StyleguideFieldUsageCustomComponent },
      { name: 'StyleguideFieldUsageDate', type: StyleguideFieldUsageDateComponent },
      { name: 'StyleguideFieldUsageFile', type: StyleguideFieldUsageFileComponent },
      { name: 'StyleguideFieldUsageImage', type: StyleguideFieldUsageImageComponent },
      { name: 'StyleguideFieldUsageItemLink', type: StyleguideFieldUsageItemLinkComponent },
      { name: 'StyleguideFieldUsageLink', type: StyleguideFieldUsageLinkComponent },
      { name: 'StyleguideFieldUsageNumber', type: StyleguideFieldUsageNumberComponent },
      { name: 'StyleguideFieldUsageRichText', type: StyleguideFieldUsageRichTextComponent },
      { name: 'StyleguideFieldUsageText', type: StyleguideFieldUsageTextComponent },
      { name: 'StyleguideLayout', type: StyleguideLayoutComponent },
      { name: 'StyleguideLayoutReuse', type: StyleguideLayoutReuseComponent },
      { name: 'StyleguideLayoutTabs', type: StyleguideLayoutTabsComponent },
      { name: 'StyleguideLayoutTabsTab', type: StyleguideLayoutTabsTabComponent },
      { name: 'StyleguideMultilingual', type: StyleguideMultilingualComponent },
      { name: 'StyleguideRouteFields', type: StyleguideRouteFieldsComponent },
      { name: 'StyleguideSection', type: StyleguideSectionComponent },
      { name: 'StyleguideSitecoreContext', type: StyleguideSitecoreContextComponent },
      { name: 'StyleguideTracking', type: StyleguideTrackingComponent },
    ], [
      { path: 'StyleguideAngularLazyLoading', loadChildren: () => import('./styleguide-angular-lazy-loading/styleguide-angular-lazy-loading.module').then(m => m.StyleguideAngularLazyLoadingModule) },
    ]),
  ],
  exports: [
    JssModule,
    AppComponentsSharedModule,
  ],
  declarations: [
    ContentBlockComponent,
    GraphQLConnectedDemoComponent,
    GraphQLIntegratedDemoComponent,
    GraphQLLayoutComponent,
    StyleguideComponentParamsComponent,
    StyleguideCustomRouteTypeComponent,
    StyleguideEditFrameComponent,
    StyleguideFieldUsageCheckboxComponent,
    StyleguideFieldUsageContentListComponent,
    StyleguideFieldUsageCustomComponent,
    StyleguideFieldUsageDateComponent,
    StyleguideFieldUsageFileComponent,
    StyleguideFieldUsageImageComponent,
    StyleguideFieldUsageItemLinkComponent,
    StyleguideFieldUsageLinkComponent,
    StyleguideFieldUsageNumberComponent,
    StyleguideFieldUsageRichTextComponent,
    StyleguideFieldUsageTextComponent,
    StyleguideLayoutComponent,
    StyleguideLayoutReuseComponent,
    StyleguideLayoutTabsComponent,
    StyleguideLayoutTabsTabComponent,
    StyleguideMultilingualComponent,
    StyleguideRouteFieldsComponent,
    StyleguideSectionComponent,
    StyleguideSitecoreContextComponent,
    StyleguideTrackingComponent,
  ],
})
export class AppComponentsModule { }
